### ISSUE TITLE
Allow multiple args records

### ISSUE THREAD

**Issue by nipafx** [nipafx/record-args#5]
At the moment, `Args.parse` accepts a single type and returns an instance of it. Instead, it could accept several types and return one instance for each. This would benefit applications with many arguments or apps/frameworks with a desire to split responsibilities for args between different parts of the code.

**Comment by hd42** [comment]
Maybe just use nested args?

record ServerArgs(String url, Optional<Integer> port){}
record LoggingArgs(String logLevel){}
record MyArgs(String foo, ServerArgs serverArgs, LoggingArgs loggingArgs){}

Then recognise that the parameter types ServerArgs and LoggingArgs are themselves records, so they are not treated as --serverArgs parameters but their parameters are added to those of MyArgs, so that it can be called with --foo bar --url https://github.com/nipafx --port 443 --logLevel DEBUG

**Comment by nipafx** [comment]
Hey @hd42, nice of you to chime in. 😃 The idea isn't bad and I might implement that in the future (you can open a new issue if you want, e.g. "Allow hierarchical args records"), but there's one use case that I have in mind that this doesn't seem to cover: A framework parsing args for itself (to a record known at the framework's compile time) as well as for the application (to a record it doesn't know at compile time).
